/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.asm.app.ui;

import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URI;
import javax.swing.JPanel;

/**
 *
 * @author Lenovo
 */
public class AboutsUsDialog extends javax.swing.JDialog {

    private final static String LINK_FACEBOOK = "https://www.facebook.com/yeudiemmythoi";
    private final static String LINK_EMAIL = "mailto:thinhnqpd06021@fpt.edu.vn";
    private final static String LINK_GITGUB = "https://github.com/QuocThinh3009";
    private final static String LINK_ZALO = "https://zalo.me/0383914506";

    /**
     * Creates new form AboutUsDialog
     */
    public AboutsUsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        clickToOpen(jpnFaceBookIcon, LINK_FACEBOOK);
        clickToOpen(jpnEmailIcon, LINK_EMAIL);
        clickToOpen(jpnGitHubIcon, LINK_GITGUB);
        clickToOpen(jpnZaloIcon, LINK_ZALO);
    }

    private void clickToOpen(JPanel panel, String link) {
        panel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                Desktop desktop = Desktop.getDesktop();

                try {
                    desktop.browse(new URI(link));
                } catch (Exception ex) {
                }

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jpnFullname = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jpnFacebook = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jpnPhone = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jpnAddress = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jpnGmail = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jpnFaceBookIcon = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jpnEmailIcon = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jpnGitHubIcon = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jpnZaloIcon = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aboust us");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 243, 154));

        jPanel2.setBackground(new java.awt.Color(254, 254, 213));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel3.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Arial", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(32, 101, 95));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("About us");

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(5, 1));

        jpnFullname.setOpaque(false);
        jpnFullname.setLayout(new java.awt.BorderLayout(15, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(32, 101, 95));
        jLabel3.setText("Nguyễn Quốc Thịnh");
        jpnFullname.add(jLabel3, java.awt.BorderLayout.CENTER);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(32, 101, 95));
        jLabel4.setText("Fullname: ");
        jLabel4.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(110, 25));
        jpnFullname.add(jLabel4, java.awt.BorderLayout.LINE_START);

        jPanel5.add(jpnFullname);

        jpnFacebook.setOpaque(false);
        jpnFacebook.setLayout(new java.awt.BorderLayout(15, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(32, 101, 95));
        jLabel6.setText("Nguyễn Thịnh");
        jpnFacebook.add(jLabel6, java.awt.BorderLayout.CENTER);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(32, 101, 95));
        jLabel7.setText("Facebook:");
        jLabel7.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabel7.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabel7.setPreferredSize(new java.awt.Dimension(110, 25));
        jpnFacebook.add(jLabel7, java.awt.BorderLayout.LINE_START);

        jPanel5.add(jpnFacebook);

        jpnPhone.setOpaque(false);
        jpnPhone.setLayout(new java.awt.BorderLayout(15, 0));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(32, 101, 95));
        jLabel9.setText("038-3914-506");
        jpnPhone.add(jLabel9, java.awt.BorderLayout.CENTER);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(32, 101, 95));
        jLabel10.setText("Phone:");
        jLabel10.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabel10.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabel10.setPreferredSize(new java.awt.Dimension(110, 25));
        jpnPhone.add(jLabel10, java.awt.BorderLayout.LINE_START);

        jPanel5.add(jpnPhone);

        jpnAddress.setOpaque(false);
        jpnAddress.setLayout(new java.awt.BorderLayout(15, 0));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(32, 101, 95));
        jLabel12.setText("Liên Chiểu, Đà Nẵng");
        jpnAddress.add(jLabel12, java.awt.BorderLayout.CENTER);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(32, 101, 95));
        jLabel13.setText("Address: ");
        jLabel13.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabel13.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabel13.setPreferredSize(new java.awt.Dimension(110, 25));
        jpnAddress.add(jLabel13, java.awt.BorderLayout.LINE_START);

        jPanel5.add(jpnAddress);

        jpnGmail.setOpaque(false);
        jpnGmail.setLayout(new java.awt.BorderLayout(15, 0));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(32, 101, 95));
        jLabel15.setText("thinhnqpd06021@fpt.edu.vn");
        jpnGmail.add(jLabel15, java.awt.BorderLayout.CENTER);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(32, 101, 95));
        jLabel16.setText("Gmail: ");
        jLabel16.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabel16.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabel16.setPreferredSize(new java.awt.Dimension(110, 25));
        jpnGmail.add(jLabel16, java.awt.BorderLayout.LINE_START);

        jPanel5.add(jpnGmail);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jpnFaceBookIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpnFaceBookIcon.setOpaque(false);
        jpnFaceBookIcon.setLayout(new java.awt.BorderLayout(0, 2));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_facebook_40px.png"))); // NOI18N
        jpnFaceBookIcon.add(jLabel18, java.awt.BorderLayout.CENTER);

        jLabel19.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(32, 101, 95));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Facebook");
        jpnFaceBookIcon.add(jLabel19, java.awt.BorderLayout.PAGE_END);

        jPanel6.add(jpnFaceBookIcon);

        jpnEmailIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpnEmailIcon.setOpaque(false);
        jpnEmailIcon.setLayout(new java.awt.BorderLayout(0, 2));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_gmail_40px.png"))); // NOI18N
        jpnEmailIcon.add(jLabel20, java.awt.BorderLayout.CENTER);

        jLabel21.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(32, 101, 95));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Email");
        jpnEmailIcon.add(jLabel21, java.awt.BorderLayout.PAGE_END);

        jPanel6.add(jpnEmailIcon);

        jpnGitHubIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpnGitHubIcon.setOpaque(false);
        jpnGitHubIcon.setLayout(new java.awt.BorderLayout(0, 2));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_github_40px.png"))); // NOI18N
        jpnGitHubIcon.add(jLabel22, java.awt.BorderLayout.CENTER);

        jLabel23.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(32, 101, 95));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("GitHub");
        jpnGitHubIcon.add(jLabel23, java.awt.BorderLayout.PAGE_END);

        jPanel6.add(jpnGitHubIcon);

        jpnZaloIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpnZaloIcon.setOpaque(false);
        jpnZaloIcon.setLayout(new java.awt.BorderLayout(0, 2));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_zalo_40px.png"))); // NOI18N
        jpnZaloIcon.add(jLabel24, java.awt.BorderLayout.CENTER);

        jLabel25.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(32, 101, 95));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Zalo");
        jpnZaloIcon.add(jLabel25, java.awt.BorderLayout.PAGE_END);

        jPanel6.add(jpnZaloIcon);

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.GridLayout(0, 1));

        jLabel5.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(75, 75, 75));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Create by QuocThinh®");
        jPanel11.add(jLabel5);

        jLabel8.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(75, 75, 75));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Students Management Applicaction");
        jPanel11.add(jLabel8);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/background.jpg"))); // NOI18N
        jPanel4.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutsUsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutsUsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutsUsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutsUsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AboutsUsDialog dialog = new AboutsUsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jpnAddress;
    private javax.swing.JPanel jpnEmailIcon;
    private javax.swing.JPanel jpnFaceBookIcon;
    private javax.swing.JPanel jpnFacebook;
    private javax.swing.JPanel jpnFullname;
    private javax.swing.JPanel jpnGitHubIcon;
    private javax.swing.JPanel jpnGmail;
    private javax.swing.JPanel jpnPhone;
    private javax.swing.JPanel jpnZaloIcon;
    // End of variables declaration//GEN-END:variables
}
