/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.asm.app.ui;

import com.asm.app.dao.ScoreDao;
import com.asm.app.dao.StudentDao;
import com.asm.app.helpers.DataValidator;
import com.asm.app.helpers.ExcelHelper;
import com.asm.app.helpers.MessageDialogHelper;
import com.asm.app.helpers.ShareData;
import com.asm.app.helpers.StyleHelper;
import com.asm.app.model.MailSender;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;

/**
 *
 * @author Lenovo
 */
public class ExportAndSendDialog extends javax.swing.JDialog {

    /**
     * Creates new form ExportAndSendDialog
     */
    public ExportAndSendDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        StyleHelper.createButton(btnCancel, btnSend);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JLabel();
        btnSend = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        txtTo = new javax.swing.JTextField();
        lblDescribe = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        txtFilename = new javax.swing.JTextField();
        lblDescribe1 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        lblDescribe2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();
        jPanel38 = new javax.swing.JPanel();
        txtSubject = new javax.swing.JTextField();
        lblDescribe3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Export and send to email");

        jPanel2.setBackground(new java.awt.Color(255, 243, 154));

        jPanel3.setBackground(new java.awt.Color(254, 254, 213));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        btnCancel.setBackground(new java.awt.Color(220, 53, 69));
        btnCancel.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(51, 51, 51));
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancel.setText("Cancel");
        btnCancel.setOpaque(true);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        jPanel4.add(btnCancel);

        btnSend.setBackground(new java.awt.Color(40, 167, 69));
        btnSend.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        btnSend.setForeground(new java.awt.Color(51, 51, 51));
        btnSend.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSend.setText("Send");
        btnSend.setOpaque(true);
        btnSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSendMouseClicked(evt);
            }
        });
        jPanel4.add(btnSend);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 101, 95), 2), "Export and send", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 14), new java.awt.Color(32, 101, 95))); // NOI18N
        jPanel5.setOpaque(false);

        jPanel35.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        jPanel35.setOpaque(false);
        jPanel35.setLayout(new java.awt.BorderLayout(10, 0));

        txtTo.setBackground(new java.awt.Color(250, 197, 91));
        txtTo.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        txtTo.setForeground(new java.awt.Color(32, 101, 95));
        txtTo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtTo.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jPanel35.add(txtTo, java.awt.BorderLayout.CENTER);

        lblDescribe.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        lblDescribe.setForeground(new java.awt.Color(32, 101, 95));
        lblDescribe.setText("Send to");
        lblDescribe.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 2, 1));
        jPanel35.add(lblDescribe, java.awt.BorderLayout.PAGE_START);

        jPanel36.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        jPanel36.setOpaque(false);
        jPanel36.setLayout(new java.awt.BorderLayout(10, 0));

        txtFilename.setBackground(new java.awt.Color(250, 197, 91));
        txtFilename.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        txtFilename.setForeground(new java.awt.Color(32, 101, 95));
        txtFilename.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFilename.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtFilename.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jPanel36.add(txtFilename, java.awt.BorderLayout.CENTER);

        lblDescribe1.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        lblDescribe1.setForeground(new java.awt.Color(32, 101, 95));
        lblDescribe1.setText("File name:");
        lblDescribe1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 2, 1));
        jPanel36.add(lblDescribe1, java.awt.BorderLayout.PAGE_START);

        jPanel37.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        jPanel37.setOpaque(false);
        jPanel37.setLayout(new java.awt.BorderLayout(10, 0));

        lblDescribe2.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        lblDescribe2.setForeground(new java.awt.Color(32, 101, 95));
        lblDescribe2.setText("Content:");
        lblDescribe2.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 2, 1));
        jPanel37.add(lblDescribe2, java.awt.BorderLayout.PAGE_START);

        txtContent.setBackground(new java.awt.Color(250, 197, 91));
        txtContent.setColumns(20);
        txtContent.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        txtContent.setForeground(new java.awt.Color(32, 101, 95));
        txtContent.setRows(5);
        jScrollPane1.setViewportView(txtContent);

        jPanel37.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel38.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        jPanel38.setOpaque(false);
        jPanel38.setLayout(new java.awt.BorderLayout(10, 0));

        txtSubject.setBackground(new java.awt.Color(250, 197, 91));
        txtSubject.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        txtSubject.setForeground(new java.awt.Color(32, 101, 95));
        txtSubject.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSubject.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtSubject.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jPanel38.add(txtSubject, java.awt.BorderLayout.CENTER);

        lblDescribe3.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        lblDescribe3.setForeground(new java.awt.Color(32, 101, 95));
        lblDescribe3.setText("Subject:");
        lblDescribe3.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 2, 1));
        jPanel38.add(lblDescribe3, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 9, Short.MAX_VALUE))
                        .addComponent(jPanel35, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                        .addComponent(jPanel36, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                        .addComponent(jPanel38, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnSendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendMouseClicked

        StringBuilder sb = new StringBuilder();

        DataValidator.valiDateEmpty(txtTo, sb, "Recever can\'t empty", new Color(250, 197, 91));
        DataValidator.valiDateEmpty(txtFilename, sb, "Filename can\'t empty", new Color(250, 197, 91));

        if (!sb.isEmpty()) {
            return;
        }
        
        String to = txtTo.getText();

        String subject = txtSubject.getText();

        String fileName = txtFilename.getText();
        fileName = fileName.endsWith(".xlsx") ? fileName : fileName + ".xlsx";

        String content = txtContent.getText();

        String path = System.getProperty("user.dir") + "\\" + fileName;
        System.out.println(path);
        try {

            String title;
            String[] header;
            ArrayList<Object> list;

            switch (ShareData.userLogin.getRole()) {
                case 1:
                    title = "List Score";
                    header = new String[]{
                        "ID",
                        "Fullname",
                        "English",
                        "Java",
                        "SQL Server",
                        "Avegare"
                    };
                    list = new ArrayList<>(new ScoreDao().getScores());
                    break;
                case 2:
                    title = "List Student";
                    header = new String[]{
                        "ID",
                        "Fullname",
                        "Gender",
                        "Email",
                        "Phone number",
                        "Address"
                    };
                    list = new ArrayList<>(new StudentDao().getStudents());
                    break;
                default:
                    return;
            }

            ExcelHelper ec = new ExcelHelper();
            ec.createFile(path, title, header, list);

            File file = new File(path);

            MailSender sender = new MailSender("thinhnq3009@gmail.com", "ysxxfxfqvlkjroya");
            sender.send(to, subject, content, file);
            MessageDialogHelper.showMessageDialog(this, "Successfully sent file to " + to, null);
            file.delete();
            this.dispose();
        } catch (Exception ex) {
            MessageDialogHelper.showErrorDialog(this, ex.getMessage(), null);
        }
    }//GEN-LAST:event_btnSendMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportAndSendDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportAndSendDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportAndSendDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportAndSendDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExportAndSendDialog dialog = new ExportAndSendDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnSend;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescribe;
    private javax.swing.JLabel lblDescribe1;
    private javax.swing.JLabel lblDescribe2;
    private javax.swing.JLabel lblDescribe3;
    private javax.swing.JTextArea txtContent;
    private javax.swing.JTextField txtFilename;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
