/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.asm.app.ui;

import com.asm.app.helpers.StyleHelper;
import com.asm.app.dao.ScoreAndInforDao;
import com.asm.app.dao.ScoreDao;
import com.asm.app.dao.StudentDao;
import com.asm.app.helpers.ExcelHelper;
import com.asm.app.helpers.MessageDialogHelper;
import com.asm.app.helpers.ShareData;
import com.asm.app.model.Score;
import com.asm.app.model.User;
import com.asm.app.model.ScoreAndInfor;
import com.asm.app.model.Students;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Lenovo
 */
public class MainForm extends javax.swing.JFrame {

    static int xMouse;
    static int yMouse;

    /**
     * Creates new form NewJFrame
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);

        StyleHelper.createButton(btnLogout, btnStudentsManagement, btnScoreManagement, btnAboutUs);

        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbContainer = new javax.swing.JToolBar();
        btnLogout = new javax.swing.JLabel();
        btnStudentsManagement = new javax.swing.JLabel();
        btnScoreManagement = new javax.swing.JLabel();
        btnAboutUs = new javax.swing.JLabel();
        pnTabedContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblAccount = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miStudentsManagement = new javax.swing.JMenuItem();
        miScoreManagement = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        mbManagement = new javax.swing.JMenu();
        miExportTo = new javax.swing.JMenuItem();
        miSendTo = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(254, 254, 213));

        jtbContainer.setBackground(new java.awt.Color(250, 250, 187));
        jtbContainer.setRollover(true);
        jtbContainer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnLogout.setBackground(new java.awt.Color(250, 250, 187));
        btnLogout.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(32, 101, 95));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_logout_rounded_left_45px.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 10, 10, 15));
        btnLogout.setOpaque(true);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        jtbContainer.add(btnLogout);

        btnStudentsManagement.setBackground(new java.awt.Color(250, 250, 187));
        btnStudentsManagement.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnStudentsManagement.setForeground(new java.awt.Color(32, 101, 95));
        btnStudentsManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_student_male_45px.png"))); // NOI18N
        btnStudentsManagement.setText("Sudents Management");
        btnStudentsManagement.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 10, 10, 15));
        btnStudentsManagement.setOpaque(true);
        btnStudentsManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStudentsManagementMouseClicked(evt);
            }
        });
        jtbContainer.add(btnStudentsManagement);

        btnScoreManagement.setBackground(new java.awt.Color(250, 250, 187));
        btnScoreManagement.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnScoreManagement.setForeground(new java.awt.Color(32, 101, 95));
        btnScoreManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_scorecard_45px.png"))); // NOI18N
        btnScoreManagement.setText("Score Management");
        btnScoreManagement.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 10, 10, 15));
        btnScoreManagement.setOpaque(true);
        btnScoreManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnScoreManagementMouseClicked(evt);
            }
        });
        jtbContainer.add(btnScoreManagement);

        btnAboutUs.setBackground(new java.awt.Color(250, 250, 187));
        btnAboutUs.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAboutUs.setForeground(new java.awt.Color(32, 101, 95));
        btnAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_about_45px.png"))); // NOI18N
        btnAboutUs.setText("About us");
        btnAboutUs.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 10, 10, 15));
        btnAboutUs.setOpaque(true);
        btnAboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutUsMouseClicked(evt);
            }
        });
        jtbContainer.add(btnAboutUs);

        pnTabedContainer.setBackground(new java.awt.Color(247, 247, 203));
        pnTabedContainer.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 187));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_administrator_male_38px_1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(250, 250, 187));
        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        lblAccount.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblAccount.setForeground(new java.awt.Color(32, 101, 95));
        lblAccount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAccount.setText("Username login");
        lblAccount.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblAccount.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 25));
        jPanel2.add(lblAccount);

        lblRole.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lblRole.setForeground(new java.awt.Color(32, 101, 95));
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRole.setText("User's role");
        lblRole.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblRole.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 25));
        jPanel2.add(lblRole);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(255, 243, 154));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(32, 101, 95));
        jMenuBar1.setOpaque(true);

        jMenu1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        jMenu1.setForeground(new java.awt.Color(32, 101, 95));
        jMenu1.setText("System");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem2.setBackground(new java.awt.Color(255, 243, 154));
        jMenuItem2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(32, 101, 95));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_logout_20px_1.png"))); // NOI18N
        jMenuItem2.setText("Logout");
        jMenuItem2.setOpaque(true);
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem3.setBackground(new java.awt.Color(255, 243, 154));
        jMenuItem3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(32, 101, 95));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_shutdown_20px.png"))); // NOI18N
        jMenuItem3.setText("Exit");
        jMenuItem3.setOpaque(true);
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        jMenu2.setForeground(new java.awt.Color(32, 101, 95));
        jMenu2.setText("View");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miStudentsManagement.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        miStudentsManagement.setBackground(new java.awt.Color(255, 243, 154));
        miStudentsManagement.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        miStudentsManagement.setForeground(new java.awt.Color(32, 101, 95));
        miStudentsManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_student_male_20px.png"))); // NOI18N
        miStudentsManagement.setText("Students Management");
        miStudentsManagement.setOpaque(true);
        jMenu2.add(miStudentsManagement);

        miScoreManagement.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        miScoreManagement.setBackground(new java.awt.Color(255, 243, 154));
        miScoreManagement.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        miScoreManagement.setForeground(new java.awt.Color(32, 101, 95));
        miScoreManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_scorecard_20px.png"))); // NOI18N
        miScoreManagement.setText("Score Management");
        miScoreManagement.setOpaque(true);
        jMenu2.add(miScoreManagement);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        jMenu3.setForeground(new java.awt.Color(32, 101, 95));
        jMenu3.setText("Account");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setBackground(new java.awt.Color(255, 243, 154));
        jMenuItem4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(32, 101, 95));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_password_20px.png"))); // NOI18N
        jMenuItem4.setText("Change Password");
        jMenuItem4.setOpaque(true);
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        mbManagement.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        mbManagement.setForeground(new java.awt.Color(32, 101, 95));
        mbManagement.setText("Management");
        mbManagement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mbManagement.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        miExportTo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miExportTo.setBackground(new java.awt.Color(255, 243, 154));
        miExportTo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        miExportTo.setForeground(new java.awt.Color(32, 101, 95));
        miExportTo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_microsoft_excel_2019_20px.png"))); // NOI18N
        miExportTo.setText("Export to");
        miExportTo.setOpaque(true);
        miExportTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExportToActionPerformed(evt);
            }
        });
        mbManagement.add(miExportTo);

        miSendTo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miSendTo.setBackground(new java.awt.Color(255, 243, 154));
        miSendTo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        miSendTo.setForeground(new java.awt.Color(32, 101, 95));
        miSendTo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_mail_20px.png"))); // NOI18N
        miSendTo.setText("Send to");
        miSendTo.setOpaque(true);
        miSendTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSendToActionPerformed(evt);
            }
        });
        mbManagement.add(miSendTo);

        jMenuBar1.add(mbManagement);

        jMenu5.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 20));
        jMenu5.setForeground(new java.awt.Color(32, 101, 95));
        jMenu5.setText("Help");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem9.setBackground(new java.awt.Color(255, 243, 154));
        jMenuItem9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem9.setForeground(new java.awt.Color(32, 101, 95));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_about_20px.png"))); // NOI18N
        jMenuItem9.setText("About us");
        jMenuItem9.setOpaque(true);
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTabedContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtbContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTabedContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAboutUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutUsMouseClicked
        new AboutsUsDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnAboutUsMouseClicked

    private void btnStudentsManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentsManagementMouseClicked
        // TODO add your handling code here:
        if (ShareData.userLogin.getRole() == User.TRANNING_STAFF) {
            addTabbed("Students Management", new StudentInfor());
        }
    }//GEN-LAST:event_btnStudentsManagementMouseClicked

    private void btnScoreManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnScoreManagementMouseClicked
        // TODO add your handling code here:
        if (ShareData.userLogin.getRole() == User.LECTURERS) {
            addTabbed("Students's Score Management", new StudentScore());
        }
    }//GEN-LAST:event_btnScoreManagementMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        tabbedClear();
        ShareData.userLogin = null;
        do {
            LoginDialog loginDialog = new LoginDialog(this, true);
            loginDialog.setVisible(true);
            this.processLoginSuccessful();
            if (ShareData.userLogin == null) {
                MessageDialogHelper.showMessageDialog(this, "Please login to continue !!! ", null);
            }
        } while (ShareData.userLogin == null);
        processLoginSuccessful();
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        btnLogoutMouseClicked(null);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ResetPassworDialog dialog = new ResetPassworDialog(this, true);
        dialog.username_static = ShareData.userLogin.getUsername();
        dialog.showChangePassContainer();
        dialog.setEnabledInputPass(false);

//        dialog.jpnInputVerificationCode.setVisible(false);
//        Dimension d = dialog.getSize();
//        dialog.setSize((int) d.getWidth(), (int) d.getHeight() - 69);
        dialog.lblTitleInput.setText("Enter your old password");
        dialog.setVisible(true);


    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void miExportToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExportToActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else {
                    return f.getName().toLowerCase().endsWith(".xlsx") /*|| f.getName().toLowerCase().endsWith(".png")*/;
                }
            }

            @Override
            public String getDescription() {
                return "Excel (.xlsx)";
            }
        });

        if (chooser.showSaveDialog(this) == JOptionPane.CANCEL_OPTION) {
            return;
        } else {

            String path = chooser.getSelectedFile().getPath();
            path = path.endsWith(".xlsx") ? path : path + ".xlsx";

            // 
            if (ShareData.userLogin.getRole() == User.TRANNING_STAFF) {
                String[] header = new String[]{
                    "ID",
                    "Fullname",
                    "Gender",
                    "Email",
                    "Phone number",
                    "Address"
                };

                StudentDao dao = new StudentDao();

                try {
                    ArrayList<Students> listStudent = dao.getStudents();
                    ArrayList<Object> list = new ArrayList<>(listStudent);
                    ExcelHelper eh = new ExcelHelper("Students Information");
                    eh.createFile(path, "Students Infor", header, list);
                    MessageDialogHelper.showMessageDialog(this, "Create and save file successfully", null);
                } catch (Exception e) {
                    e.printStackTrace();
                }

            } else if (ShareData.userLogin.getRole() == User.LECTURERS) {
                System.out.println("Student Score");
                String[] header = new String[]{
                    "ID",
                    "Fullname",
                    "English",
                    "Java",
                    "SQL Server",
                    "Avegare"
                };

                ScoreDao dao = new ScoreDao();

                try {
                    ArrayList<Score> listScore = dao.getScores();
                    ArrayList<Object> list = new ArrayList<>(listScore);
                    ExcelHelper eh = new ExcelHelper("Students Information");
                    eh.createFile(path, "Students Infor", header, list);
                    MessageDialogHelper.showMessageDialog(this, "Create and save file successfully", null);
                } catch (Exception e) {
                    e.printStackTrace();
                }

            }
        }


    }//GEN-LAST:event_miExportToActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        btnAboutUsMouseClicked(null);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void miSendToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSendToActionPerformed
        ExportAndSendDialog dialog = new ExportAndSendDialog(this, true);
        
        dialog.setVisible(true);
    }//GEN-LAST:event_miSendToActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainForm mainForm = new MainForm();
                mainForm.setVisible(true);
                do {
                    LoginDialog loginDialog = new LoginDialog(mainForm, true);
                    loginDialog.setVisible(true);
                    mainForm.processLoginSuccessful();
                    if (ShareData.userLogin == null) {
                        MessageDialogHelper.showMessageDialog(mainForm, "Please login to continue !!! ", null);
                    }
                } while (ShareData.userLogin == null);
            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAboutUs;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnScoreManagement;
    private javax.swing.JLabel btnStudentsManagement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jtbContainer;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblRole;
    private javax.swing.JMenu mbManagement;
    private javax.swing.JMenuItem miExportTo;
    private javax.swing.JMenuItem miScoreManagement;
    private javax.swing.JMenuItem miSendTo;
    private javax.swing.JMenuItem miStudentsManagement;
    private javax.swing.JPanel pnTabedContainer;
    // End of variables declaration//GEN-END:variables

    private void addTabbed(String tille, JPanel panel) {
        JLabel lbl = new JLabel(tille);
        lbl.setBackground(new java.awt.Color(252, 244, 179));
        lbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl.setForeground(new java.awt.Color(32, 101, 95));
        lbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 10, 2, 10));
        lbl.setOpaque(true);
        StyleHelper.createButton(lbl);

        pnTabedContainer.removeAll();

        pnTabedContainer.add(panel);

    }

    private void tabbedClear() {
        pnTabedContainer.removeAll();
    }

    private void setView(int role) {
        btnScoreManagement.setEnabled(role == 1);
        btnStudentsManagement.setEnabled(role == 2);
//        miAccountManagment.setEnabled(role == 2);
        miScoreManagement.setEnabled(role == 1);
        miStudentsManagement.setEnabled(role == 2);
        miExportTo.setEnabled(role == 1 || role == 2);
        miSendTo.setEnabled(role == 1 || role == 2);
    }

    private void processLoginSuccessful() {

        User user = ShareData.userLogin;

        if (user != null) {
            //Show infor user
            lblAccount.setText(user.getUsername());
            lblRole.setText(user.getRoleString());

            setView(user.getRole());
            // Student view ( Show only score table and infor)
            if (ShareData.userLogin.getRole() == User.STUDENT) {
                studentView();
            } else if (user.getRole() == User.LECTURERS) {
                lecturersView();

            } else if (user.getRole() == User.TRANNING_STAFF) {

                StudentInfor si = new StudentInfor();
                si.parentForm = this;
                addTabbed("Student's Information Management", si);

            }
        }
    }

    private void studentView() {

        StudentViewPanel sv = new StudentViewPanel();
        pnTabedContainer.add(sv);
        ScoreAndInforDao said = new ScoreAndInforDao();
        try {
            ScoreAndInfor si = said.getScoreAndInfor(ShareData.userLogin);
            sv.showInfor(si);
        } catch (Exception ex) {
            MessageDialogHelper.showErrorDialog(this, ex.getMessage(), "Error loading data to form !!!");
        }
    }

    private void lecturersView() {

        //Show data to display
        StudentScore ss = new StudentScore();
        addTabbed("Students's Score Management", ss);
    }

}
