/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.asm.app.ui;

import com.asm.app.helpers.Converter;
import com.asm.app.helpers.ImageHelper;
import com.asm.app.helpers.MessageDialogHelper;
import com.asm.app.helpers.StyleHelper;
import com.asm.app.model.ScoreAndInfor;
import java.io.IOException;
import javax.swing.ImageIcon;

/**
 *
 * @author Lenovo
 */
public class StudentViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentViewPanel
     */
    public StudentViewPanel() {
        initComponents();
        StyleHelper.createButton(btnlLogout, btnlReport);
    }

    public void showInfor(ScoreAndInfor si) {
        // Show Infor
        lblTitle_std.setText(si.getFullname() + " - " + si.getID());
        txtId.setText(si.getID());
        txtFullname.setText(si.getFullname());
        txtEmail.setText(si.getEmail());
        txtAddress.setText(si.getAddress());
        txtPhoneNumber.setText(si.getPhoneNumber());

        if (si.getGender() == 1) {
            rdbMale.setSelected(true);
        } else {
            rdbFemale.setSelected(true);
        }

        // Show Score
        String english = String.valueOf(si.getEnglish());
        String java = String.valueOf(si.getJava());
        String sqlServer = String.valueOf(si.getSqlSever());
        String avegare = String.valueOf(Converter.round(si.getAvegare(), 2));

        lblEnglish.setText(english);
        lblJava.setText(java);
        lblSqlServer.setText(sqlServer);
        lblAvegare.setText(avegare);

        //Show avata
        if (si.getAvata() != null) {
            try {
                ImageIcon icon = new ImageIcon(ImageHelper.createImageFromBytes(si.getAvata(), "jpg"));
                lblAvata.setIcon(icon);
            } catch (IOException ex) {
                ex.printStackTrace();
                MessageDialogHelper.showErrorDialog(this, ex.getMessage(), null);
            }
        } else {
            if (si.getGender() == 1) {
                lblAvata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_man_student_200px.png")));
            } else {
                lblAvata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_person_student_200px.png")));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel29 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        lblTitle_std = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lblEnglish = new javax.swing.JLabel();
        lblJava = new javax.swing.JLabel();
        lblSqlServer = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        lblAvegare = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        btnlReport = new javax.swing.JLabel();
        btnlLogout = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jpnContainerInput1 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jPanel35 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        jPanel36 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        rdbFemale = new javax.swing.JRadioButton();
        rdbMale = new javax.swing.JRadioButton();
        jPanel38 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jPanel39 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        jPanel40 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jPanel42 = new javax.swing.JPanel();
        lblAvata = new javax.swing.JLabel();

        jPanel29.setBackground(new java.awt.Color(255, 243, 154));

        jPanel17.setBackground(new java.awt.Color(254, 254, 213));

        lblTitle_std.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        lblTitle_std.setForeground(new java.awt.Color(32, 101, 95));
        lblTitle_std.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_std.setText("Student's Name - Student's ID");

        jPanel27.setOpaque(false);

        jPanel28.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel28.setOpaque(false);
        jPanel28.setLayout(new java.awt.GridLayout(2, 3, 5, 10));

        jLabel34.setBackground(new java.awt.Color(255, 255, 204));
        jLabel34.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(32, 101, 95));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("English");
        jLabel34.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel34.setOpaque(true);
        jPanel28.add(jLabel34);

        jLabel36.setBackground(new java.awt.Color(255, 255, 204));
        jLabel36.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(32, 101, 95));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Java");
        jLabel36.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel36.setOpaque(true);
        jPanel28.add(jLabel36);

        jLabel35.setBackground(new java.awt.Color(255, 255, 204));
        jLabel35.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(32, 101, 95));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("SQL Sever");
        jLabel35.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel35.setOpaque(true);
        jPanel28.add(jLabel35);

        lblEnglish.setBackground(new java.awt.Color(204, 255, 204));
        lblEnglish.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        lblEnglish.setForeground(new java.awt.Color(32, 101, 95));
        lblEnglish.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnglish.setText("9.99");
        lblEnglish.setOpaque(true);
        jPanel28.add(lblEnglish);

        lblJava.setBackground(new java.awt.Color(204, 255, 204));
        lblJava.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        lblJava.setForeground(new java.awt.Color(32, 101, 95));
        lblJava.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJava.setText("9.99");
        lblJava.setOpaque(true);
        jPanel28.add(lblJava);

        lblSqlServer.setBackground(new java.awt.Color(204, 255, 204));
        lblSqlServer.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        lblSqlServer.setForeground(new java.awt.Color(32, 101, 95));
        lblSqlServer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSqlServer.setText("9.99");
        lblSqlServer.setOpaque(true);
        jPanel28.add(lblSqlServer);

        jPanel30.setOpaque(false);
        jPanel30.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        jPanel31.setBackground(new java.awt.Color(204, 255, 204));
        jPanel31.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        jPanel31.setLayout(new java.awt.BorderLayout());

        jLabel45.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(32, 101, 95));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Avegare");
        jPanel31.add(jLabel45, java.awt.BorderLayout.PAGE_START);

        lblAvegare.setFont(new java.awt.Font("Arial", 3, 38)); // NOI18N
        lblAvegare.setForeground(new java.awt.Color(32, 101, 95));
        lblAvegare.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvegare.setText("9.99");
        jPanel31.add(lblAvegare, java.awt.BorderLayout.CENTER);

        jPanel30.add(jPanel31);

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel32.setOpaque(false);
        jPanel32.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        btnlReport.setBackground(new java.awt.Color(255, 146, 52));
        btnlReport.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        btnlReport.setForeground(new java.awt.Color(16, 51, 48));
        btnlReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnlReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_urgent_message_30px.png"))); // NOI18N
        btnlReport.setText("Report");
        btnlReport.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        btnlReport.setOpaque(true);
        jPanel32.add(btnlReport);

        btnlLogout.setBackground(new java.awt.Color(255, 146, 52));
        btnlLogout.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        btnlLogout.setForeground(new java.awt.Color(16, 51, 48));
        btnlLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_logout_30px.png"))); // NOI18N
        btnlLogout.setText("Log out");
        btnlLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        btnlLogout.setOpaque(true);
        btnlLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlLogoutMouseClicked(evt);
            }
        });
        jPanel32.add(btnlLogout);

        jpnContainerInput1.setBackground(new java.awt.Color(247, 247, 176));
        jpnContainerInput1.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7));
        jpnContainerInput1.setLayout(new java.awt.GridLayout(6, 0, 0, 5));

        jPanel34.setOpaque(false);
        jPanel34.setLayout(new java.awt.BorderLayout(15, 0));

        jLabel44.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(32, 101, 95));
        jLabel44.setText("ID:");
        jLabel44.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jLabel44.setMaximumSize(new java.awt.Dimension(116, 19));
        jLabel44.setMinimumSize(new java.awt.Dimension(116, 19));
        jLabel44.setPreferredSize(new java.awt.Dimension(116, 19));
        jPanel34.add(jLabel44, java.awt.BorderLayout.LINE_START);

        txtId.setBackground(new java.awt.Color(254, 254, 213));
        txtId.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        txtId.setForeground(new java.awt.Color(32, 101, 95));
        txtId.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        txtId.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        txtId.setEnabled(false);
        jPanel34.add(txtId, java.awt.BorderLayout.CENTER);

        jpnContainerInput1.add(jPanel34);

        jPanel35.setOpaque(false);
        jPanel35.setLayout(new java.awt.BorderLayout(15, 0));

        jLabel49.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(32, 101, 95));
        jLabel49.setText("Fullname:");
        jLabel49.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jLabel49.setMaximumSize(new java.awt.Dimension(116, 19));
        jLabel49.setMinimumSize(new java.awt.Dimension(116, 19));
        jLabel49.setPreferredSize(new java.awt.Dimension(116, 19));
        jPanel35.add(jLabel49, java.awt.BorderLayout.LINE_START);

        txtFullname.setBackground(new java.awt.Color(254, 254, 213));
        txtFullname.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        txtFullname.setForeground(new java.awt.Color(32, 101, 95));
        txtFullname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        txtFullname.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        txtFullname.setEnabled(false);
        jPanel35.add(txtFullname, java.awt.BorderLayout.CENTER);

        jpnContainerInput1.add(jPanel35);

        jPanel36.setOpaque(false);
        jPanel36.setLayout(new java.awt.BorderLayout(15, 0));

        jLabel50.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(32, 101, 95));
        jLabel50.setText("Gender:");
        jLabel50.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jLabel50.setMaximumSize(new java.awt.Dimension(116, 19));
        jLabel50.setMinimumSize(new java.awt.Dimension(116, 19));
        jLabel50.setPreferredSize(new java.awt.Dimension(116, 19));
        jPanel36.add(jLabel50, java.awt.BorderLayout.LINE_START);

        jPanel37.setOpaque(false);
        jPanel37.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 30, 5));

        rdbFemale.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        rdbFemale.setForeground(new java.awt.Color(32, 101, 95));
        rdbFemale.setText("Female");
        rdbFemale.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 1, 1));
        rdbFemale.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        rdbFemale.setEnabled(false);
        jPanel37.add(rdbFemale);

        rdbMale.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        rdbMale.setForeground(new java.awt.Color(32, 101, 95));
        rdbMale.setText("Male");
        rdbMale.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 1, 1));
        rdbMale.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        rdbMale.setEnabled(false);
        jPanel37.add(rdbMale);

        jPanel36.add(jPanel37, java.awt.BorderLayout.CENTER);

        jpnContainerInput1.add(jPanel36);

        jPanel38.setOpaque(false);
        jPanel38.setLayout(new java.awt.BorderLayout(15, 0));

        jLabel51.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(32, 101, 95));
        jLabel51.setText("Email:");
        jLabel51.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jLabel51.setMaximumSize(new java.awt.Dimension(116, 19));
        jLabel51.setMinimumSize(new java.awt.Dimension(116, 19));
        jLabel51.setPreferredSize(new java.awt.Dimension(116, 19));
        jPanel38.add(jLabel51, java.awt.BorderLayout.LINE_START);

        txtEmail.setBackground(new java.awt.Color(254, 254, 213));
        txtEmail.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(32, 101, 95));
        txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        txtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        txtEmail.setEnabled(false);
        jPanel38.add(txtEmail, java.awt.BorderLayout.CENTER);

        jpnContainerInput1.add(jPanel38);

        jPanel39.setOpaque(false);
        jPanel39.setLayout(new java.awt.BorderLayout(15, 0));

        jLabel52.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(32, 101, 95));
        jLabel52.setText("Phone number:");
        jLabel52.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jPanel39.add(jLabel52, java.awt.BorderLayout.LINE_START);

        txtPhoneNumber.setBackground(new java.awt.Color(254, 254, 213));
        txtPhoneNumber.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        txtPhoneNumber.setForeground(new java.awt.Color(32, 101, 95));
        txtPhoneNumber.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        txtPhoneNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        txtPhoneNumber.setEnabled(false);
        jPanel39.add(txtPhoneNumber, java.awt.BorderLayout.CENTER);

        jpnContainerInput1.add(jPanel39);

        jPanel40.setOpaque(false);
        jPanel40.setLayout(new java.awt.BorderLayout(15, 0));

        jLabel53.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(32, 101, 95));
        jLabel53.setText("Address:");
        jLabel53.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jLabel53.setMaximumSize(new java.awt.Dimension(116, 19));
        jLabel53.setMinimumSize(new java.awt.Dimension(116, 19));
        jLabel53.setPreferredSize(new java.awt.Dimension(116, 19));
        jPanel40.add(jLabel53, java.awt.BorderLayout.LINE_START);

        txtAddress.setBackground(new java.awt.Color(254, 254, 213));
        txtAddress.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(32, 101, 95));
        txtAddress.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        txtAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        txtAddress.setEnabled(false);
        jPanel40.add(txtAddress, java.awt.BorderLayout.CENTER);

        jpnContainerInput1.add(jPanel40);

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel33Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpnContainerInput1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
            .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel33Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpnContainerInput1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel42.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel42.setMaximumSize(new java.awt.Dimension(173, 230));
        jPanel42.setMinimumSize(new java.awt.Dimension(173, 230));
        jPanel42.setOpaque(false);

        lblAvata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAvata, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAvata, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitle_std, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle_std, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 58, Short.MAX_VALUE)
                .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
            .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel29Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
            .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel29Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnlLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlLogoutMouseClicked

    }//GEN-LAST:event_btnlLogoutMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel btnlLogout;
    protected javax.swing.JLabel btnlReport;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jpnContainerInput1;
    public javax.swing.JLabel lblAvata;
    public javax.swing.JLabel lblAvegare;
    public javax.swing.JLabel lblEnglish;
    public javax.swing.JLabel lblJava;
    public javax.swing.JLabel lblSqlServer;
    public javax.swing.JLabel lblTitle_std;
    public javax.swing.JRadioButton rdbFemale;
    public javax.swing.JRadioButton rdbMale;
    public javax.swing.JTextField txtAddress;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtFullname;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
