/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.asm.app.ui;

import com.asm.app.dao.ScoreDao;
import com.asm.app.helpers.Converter;
import com.asm.app.helpers.DataValidator;
import com.asm.app.helpers.MessageDialogHelper;
import com.asm.app.helpers.ShareData;
import com.asm.app.helpers.StyleHelper;
import com.asm.app.model.Score;
import com.asm.app.model.Students;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class StudentScore extends javax.swing.JPanel {

    public static int currentIndex;
    public static ArrayList<Score> list = ShareData.listScore;
    public static boolean showTop3 = false;

    /**
     * Creates new form StudentScore
     */
    public StudentScore() {
        initComponents();
        fillTable();
        showScore(list.get(0));
        StyleHelper.designTable(tblStudents);
    }

    private void fillTable() {

        try {
            list = new ScoreDao().getScores();
        } catch (Exception ex) {
            MessageDialogHelper.showErrorDialog(this, "Can't load data", null);
        }

        String[] columnNames = {
            "Student's ID",
            "Fullname",
            "English",
            "Java",
            "SQL Server",
            "Avegare"
        };

        Object[][] data = new Object[list.size()][6];

        for (int i = 0; i < list.size(); i++) {
            Score score = list.get(i);
            data[i][0] = score.getIdStudent();
            data[i][1] = score.getFullname();
            data[i][2] = score.getEnligsh();
            data[i][3] = score.getJava();
            data[i][4] = score.getSqlServer();
            data[i][5] = Converter.round(score.getAvegare(), 2);

        }

        tblStudents.setModel(new DefaultTableModel(data, columnNames));
    }

    private void showScore(Score score) {
        lblFullname.setText(score.getFullname());
        lblIdStudent.setText(score.getIdStudent());
        txtEnglish.setText(String.valueOf(score.getEnligsh()));
        txtJava.setText(String.valueOf(score.getJava()));
        txtSqlServer.setText(String.valueOf(score.getSqlServer()));
        txtAvegare.setText(String.valueOf(score.getAvegare()));
    }

    private String validateScore() {
        StringBuilder sb = new StringBuilder();

        DataValidator.validateScore(txtEnglish, sb, "English score is not in the correct format");
        DataValidator.validateScore(txtJava, sb, "Java score is not in the correct format");
        DataValidator.validateScore(txtSqlServer, sb, "SQL Server score is not in the correct format");

        if (!sb.isEmpty()) {
            MessageDialogHelper.showErrorDialog(this, sb.toString(), null);
        }

        return sb.toString();
    }

    private Score readForm() {
        String idStudent = lblIdStudent.getText();
        String fullname = lblFullname.getText();

        String str_english = txtEnglish.getText();
        str_english = (str_english.contains(",")) ? str_english.replace(',', '.') : str_english;
        double english = Double.parseDouble(str_english);

        String str_java = txtJava.getText();
        str_java = (str_java.contains(",")) ? str_java.replace(',', '.') : str_java;
        double java = Double.parseDouble(str_java);

        String str_sqlServer = txtSqlServer.getText();
        str_sqlServer = (str_sqlServer.contains(",")) ? str_sqlServer.replace(',', '.') : str_sqlServer;
        double sqlServer = Double.parseDouble(str_sqlServer);

        return new Score(idStudent, fullname, english, java, sqlServer);
    }

    private void setAvegare() {
        Thread thread = new Thread() {
            @Override
            public void run() {
                try {
                    sleep(50);
                    Score score = readForm();
                    txtAvegare.setText(String.valueOf(score.getAvegare()));
                } catch (InterruptedException ex) {
                } catch (Exception e) {
                    txtAvegare.setText("Error");
                }

            }

        };
        thread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtFind = new javax.swing.JTextField();
        btnlFind = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblFullname = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblIdStudent = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtEnglish = new javax.swing.JTextField();
        txtJava = new javax.swing.JTextField();
        txtSqlServer = new javax.swing.JTextField();
        txtAvegare = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        btnlFirst = new javax.swing.JLabel();
        btnlPrev = new javax.swing.JLabel();
        btnNext = new javax.swing.JLabel();
        btnLast = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        btnNew = new javax.swing.JLabel();
        btnSave = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JLabel();
        btnTop3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 243, 154));
        setMaximumSize(new java.awt.Dimension(765, 542));
        setMinimumSize(new java.awt.Dimension(765, 542));
        setPreferredSize(new java.awt.Dimension(765, 542));

        jPanel6.setBackground(new java.awt.Color(254, 254, 213));
        jPanel6.setForeground(new java.awt.Color(254, 254, 213));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(32, 101, 95));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Students's Score Information");

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.BorderLayout(10, 0));

        txtFind.setBackground(new java.awt.Color(250, 197, 91));
        txtFind.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        txtFind.setForeground(new java.awt.Color(32, 101, 95));
        txtFind.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        jPanel5.add(txtFind, java.awt.BorderLayout.CENTER);

        btnlFind.setBackground(new java.awt.Color(255, 146, 52));
        btnlFind.setFont(new java.awt.Font("Arial", 1, 21)); // NOI18N
        btnlFind.setForeground(new java.awt.Color(16, 51, 48));
        btnlFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_find_and_replace_30px.png"))); // NOI18N
        btnlFind.setText("Find");
        btnlFind.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        btnlFind.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlFind.setOpaque(true);
        btnlFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlFindMouseClicked(evt);
            }
        });
        jPanel5.add(btnlFind, java.awt.BorderLayout.LINE_END);

        jPanel7.setOpaque(false);

        jPanel8.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Arial", 2, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(32, 101, 95));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Fullname: ");

        lblFullname.setBackground(new java.awt.Color(255, 214, 133));
        lblFullname.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblFullname.setForeground(new java.awt.Color(32, 101, 95));
        lblFullname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFullname.setText("Nguyen Quoc Thinh");
        lblFullname.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 3, 5, 10));

        jLabel8.setFont(new java.awt.Font("Arial", 2, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(32, 101, 95));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("ID:");

        lblIdStudent.setBackground(new java.awt.Color(255, 214, 133));
        lblIdStudent.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblIdStudent.setForeground(new java.awt.Color(32, 101, 95));
        lblIdStudent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIdStudent.setText("PD06021");
        lblIdStudent.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 3, 5, 10));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFullname, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIdStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIdStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 189));
        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 7, 15, 7));
        jPanel9.setLayout(new java.awt.GridLayout(2, 4, 15, 5));

        jLabel11.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(32, 101, 95));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("English");
        jPanel9.add(jLabel11);

        jLabel12.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(32, 101, 95));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Java");
        jPanel9.add(jLabel12);

        jLabel10.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(32, 101, 95));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SQL Server");
        jPanel9.add(jLabel10);

        jLabel13.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(32, 101, 95));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Average Score");
        jPanel9.add(jLabel13);

        txtEnglish.setBackground(new java.awt.Color(204, 255, 204));
        txtEnglish.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtEnglish.setForeground(new java.awt.Color(32, 101, 95));
        txtEnglish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEnglish.setText("9.99");
        txtEnglish.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEnglishFocusLost(evt);
            }
        });
        txtEnglish.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEnglishKeyPressed(evt);
            }
        });
        jPanel9.add(txtEnglish);

        txtJava.setBackground(new java.awt.Color(204, 255, 204));
        txtJava.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtJava.setForeground(new java.awt.Color(32, 101, 95));
        txtJava.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtJava.setText("9.99");
        txtJava.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJavaKeyPressed(evt);
            }
        });
        jPanel9.add(txtJava);

        txtSqlServer.setBackground(new java.awt.Color(204, 255, 204));
        txtSqlServer.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtSqlServer.setForeground(new java.awt.Color(32, 101, 95));
        txtSqlServer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSqlServer.setText("9.99");
        txtSqlServer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSqlServerKeyPressed(evt);
            }
        });
        jPanel9.add(txtSqlServer);

        txtAvegare.setEditable(false);
        txtAvegare.setBackground(new java.awt.Color(204, 255, 204));
        txtAvegare.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtAvegare.setForeground(new java.awt.Color(32, 101, 95));
        txtAvegare.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAvegare.setText("9.99");
        txtAvegare.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        txtAvegare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvegareActionPerformed(evt);
            }
        });
        jPanel9.add(txtAvegare);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        jPanel11.setBackground(new java.awt.Color(242, 242, 138));
        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

        btnlFirst.setBackground(new java.awt.Color(255, 146, 52));
        btnlFirst.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnlFirst.setForeground(new java.awt.Color(16, 51, 48));
        btnlFirst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnlFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_skip_to_start_30px.png"))); // NOI18N
        btnlFirst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlFirst.setOpaque(true);
        btnlFirst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlFirstMouseClicked(evt);
            }
        });
        jPanel11.add(btnlFirst);

        btnlPrev.setBackground(new java.awt.Color(255, 146, 52));
        btnlPrev.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnlPrev.setForeground(new java.awt.Color(16, 51, 48));
        btnlPrev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnlPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_rewind_30px.png"))); // NOI18N
        btnlPrev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlPrev.setOpaque(true);
        btnlPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlPrevMouseClicked(evt);
            }
        });
        jPanel11.add(btnlPrev);

        btnNext.setBackground(new java.awt.Color(255, 146, 52));
        btnNext.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(16, 51, 48));
        btnNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_fast_forward_30px.png"))); // NOI18N
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.setOpaque(true);
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });
        jPanel11.add(btnNext);

        btnLast.setBackground(new java.awt.Color(255, 146, 52));
        btnLast.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnLast.setForeground(new java.awt.Color(16, 51, 48));
        btnLast.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_end_30px.png"))); // NOI18N
        btnLast.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLast.setOpaque(true);
        btnLast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLastMouseClicked(evt);
            }
        });
        jPanel11.add(btnLast);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 82, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(200, 200, 200))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        btnNew.setBackground(new java.awt.Color(255, 146, 52));
        btnNew.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNew.setForeground(new java.awt.Color(16, 51, 48));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_add_new_30px.png"))); // NOI18N
        btnNew.setText("New");
        btnNew.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 25, 5, 25));
        btnNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNew.setOpaque(true);
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewMouseClicked(evt);
            }
        });
        jPanel12.add(btnNew);

        btnSave.setBackground(new java.awt.Color(255, 146, 52));
        btnSave.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(16, 51, 48));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_save_30px.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 25, 5, 25));
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setOpaque(true);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        jPanel12.add(btnSave);

        btnDelete.setBackground(new java.awt.Color(255, 146, 52));
        btnDelete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(16, 51, 48));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_remove_30px.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 25, 5, 25));
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setOpaque(true);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        jPanel12.add(btnDelete);

        btnUpdate.setBackground(new java.awt.Color(255, 146, 52));
        btnUpdate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(16, 51, 48));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_upgrade_30px.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 25, 5, 25));
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setOpaque(true);
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        jPanel12.add(btnUpdate);

        btnTop3.setBackground(new java.awt.Color(255, 146, 52));
        btnTop3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnTop3.setForeground(new java.awt.Color(16, 51, 48));
        btnTop3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asm/app/icons/icons8_circled_3_30px.png"))); // NOI18N
        btnTop3.setText("Top 3");
        btnTop3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 25, 5, 25));
        btnTop3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTop3.setOpaque(true);
        btnTop3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTop3MouseClicked(evt);
            }
        });
        jPanel12.add(btnTop3);

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudents);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAvegareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvegareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvegareActionPerformed

    private void tblStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentsMouseClicked

        currentIndex = tblStudents.getSelectedRow();
        showScore(list.get(currentIndex));

    }//GEN-LAST:event_tblStudentsMouseClicked

    private void btnlFirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlFirstMouseClicked
        currentIndex = 0;
        showScore(list.get(currentIndex));

    }//GEN-LAST:event_btnlFirstMouseClicked

    private void btnLastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLastMouseClicked
        currentIndex = list.size() - 1;
        showScore(list.get(currentIndex));

    }//GEN-LAST:event_btnLastMouseClicked

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        currentIndex = (currentIndex == list.size() - 1) ? 0 : currentIndex + 1;
        showScore(list.get(currentIndex));

    }//GEN-LAST:event_btnNextMouseClicked

    private void btnlPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlPrevMouseClicked
        currentIndex = (currentIndex == 0) ? list.size() - 1 : currentIndex - 1;
        showScore(list.get(currentIndex));

    }//GEN-LAST:event_btnlPrevMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        if (validateScore().isEmpty()) {
            Score score = readForm();
            ScoreDao sd = new ScoreDao();

            try {
                if (sd.update(score)) {
                    MessageDialogHelper.showMessageDialog(this, "UPDATE successful", "Notification");
                } else {
                    MessageDialogHelper.showMessageDialog(this, "UPDATE unsuccessful", "Notification");
                }
            } catch (Exception e) {

            }
        }
        fillTable();
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void txtEnglishKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnglishKeyPressed
        setAvegare();
    }//GEN-LAST:event_txtEnglishKeyPressed

    private void txtEnglishFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEnglishFocusLost

    }//GEN-LAST:event_txtEnglishFocusLost

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        if (validateScore().isBlank()) {
            Score score = readForm();
            ScoreDao sd = new ScoreDao();

            try {
                boolean value = sd.insert(score);

                if (value) {
                    MessageDialogHelper.showMessageDialog(this, "Save score successfull", null);
                } else {
                    MessageDialogHelper.showErrorDialog(this, "Can't save score. Try again with Update button", null);

                }
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
                MessageDialogHelper.showErrorDialog(this, "Can't save score try Again", null);
            }

        }

        fillTable();
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseClicked
        SelectStudents selectStudents = new SelectStudents(null, true);
        selectStudents.setVisible(true);
        Students std = ShareData.selectNewStudent;
        if (std != null) {
            showScore(new Score(std.getID(), std.getFullname(), 0, 0, 0));
        }
    }//GEN-LAST:event_btnNewMouseClicked

    private void btnlFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlFindMouseClicked
        String key = txtFind.getText();
        ScoreDao dao = new ScoreDao();
        try {
            list = dao.getScores(key);

            DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
            model.setRowCount(0);
            System.out.println(list.size());
            for (Score s : list) {
                model.addRow(new Object[]{
                    s.getIdStudent(),
                    s.getFullname(),
                    s.getEnligsh(),
                    s.getJava(),
                    s.getSqlServer(),
                    s.getAvegare()
                });
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex.getMessage());
            MessageDialogHelper.showErrorDialog(this, "Can't find student now", null);
        }
    }//GEN-LAST:event_btnlFindMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        Score score = readForm();
        String message = score.getFullname() + " [" + score.getIdStudent() + "]";

        int option = MessageDialogHelper.showConfimDialog(this, "Are you sure DELETE " + message + " ?", "Notification");

        if (option == 0) {
            try {
                ScoreDao sd = new ScoreDao();
                boolean value = sd.delete(score);

                if (value) {
                    MessageDialogHelper.showConfimDialog(this, "DELETE " + message + " successful", "Notification");
                } else {
                    MessageDialogHelper.showConfimDialog(this, "DELETE " + message + " unsuccessful", "Notification");
                }

            } catch (Exception ex) {
                ex.printStackTrace();
                System.out.println(ex.getMessage());
                MessageDialogHelper.showErrorDialog(this, "Can't delete student now", null);
            }
        }
        fillTable();
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void txtJavaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJavaKeyPressed
        setAvegare();
    }//GEN-LAST:event_txtJavaKeyPressed

    private void txtSqlServerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSqlServerKeyPressed
        // TODO add your handling code here:
        setAvegare();
    }//GEN-LAST:event_txtSqlServerKeyPressed

    private void btnTop3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTop3MouseClicked
        showTop3 = !showTop3;
        if (showTop3) {

            ArrayList<Score> copyList = new ArrayList<>(list);

            Collections.sort(copyList, (Score o1, Score o2) -> (int) (o2.getAvegare() - o1.getAvegare()) * 1000);

            DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
            model.setRowCount(0);
            for (int i = 0; i < 3; i++) {
                Score s = copyList.get(i);
                model.addRow(new Object[]{
                    s.getIdStudent(),
                    s.getFullname(),
                    s.getEnligsh(),
                    s.getJava(),
                    s.getSqlServer(),
                    s.getAvegare()
                });
            }
        } else {
            fillTable();
        }
    }//GEN-LAST:event_btnTop3MouseClicked

    //<editor-fold defaultstate="collapsed" desc="Variable system init">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel btnLast;
    private javax.swing.JLabel btnNew;
    private javax.swing.JLabel btnNext;
    private javax.swing.JLabel btnSave;
    private javax.swing.JLabel btnTop3;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.JLabel btnlFind;
    private javax.swing.JLabel btnlFirst;
    private javax.swing.JLabel btnlPrev;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblIdStudent;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtAvegare;
    private javax.swing.JTextField txtEnglish;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtJava;
    private javax.swing.JTextField txtSqlServer;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>

}
